// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://medewwsectbpixszrcfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lZGV3d3NlY3RicGl4c3pyY2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMjExOTMsImV4cCI6MjA3MDc5NzE5M30.JcTH_iabAthhtYX9wGFMw0lMpW0ZksE3HHOMy-c-fHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});